language: go
go:
  - "master"
sudo: required
services:
  - docker

before_install:
  - cp ./dockers/Golang/run.sh ./dockers/Golang/1.12/run.sh
  - docker build -t avelino/cover.run:golang-1.12 ./dockers/Golang/1.12
