language: go
go:
  - "master"
sudo: required
services:
  - docker

before_install:
  - cp ./dockers/golang/run.sh ./dockers/golang/1.10/run.sh
  - docker build -t avelino/cover.run:golang-1.10 ./dockers/golang/1.10
