language: go
go:
  - 1.11.x
  - tip

services:
  - docker

install:
  - ls -alh
  - cp build/docker/golang/run.sh build/docker/golang/1.10/run.sh
  - docker build -t avelino/cover.run:golang-1.10 ./build/docker/golang/1.10

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
