version: "2"
services:
  cover.run:
    privileged: true
    build: .
    links:
      - redis:redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000
  redis:
    image: redis
  caddy:
    image: abiosoft/caddy
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./assets:/srv/assets
    links:
      - cover.run:cover.run
    ports:
      - 80:2015
